### ISSUE TITLE
Clicking after showing stats panel

### ISSUE THREAD

**Issue by zlindner** [zlindner/ClickManiaMMXV#1]
After clicking on the main button after checking your stats, it shows the panStats behind the button.

**Comment by zlindner** [comment]
Fixed

**Comment by ChuckBoy** [comment]
Good job.

**Comment by aiWebster** [comment]
Nice job! Keep up the good work! :-)

**Comment by DunkehX** [comment]
Great Work #DoloGwalaGang

**Comment by DunkehX** [comment]
GwalaGang
