### ISSUE TITLE
Buttons appear on every screen. Help please. ): Hitler

### ISSUE THREAD

**Issue by aiWebster** [zlindner/ClickManiaMMXV#2]
Hi.

**Comment by zlindner** [comment]
Post a pastebin snippet of the code please

**Comment by aiWebster** [comment]
package clickmaniammxv;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

public class PanOption extends JPanel {
    public PanOption() {
        setLayout(new GridLayout(1, 10));
        JButton btnSoundOn = new JButton("On"), btnSoundOff = new JButton("Off");
         ActionListener on = new PanOption.On(), off = new PanOption.Off();
        this.setBackground(Color.red);
        add(btnSoundOn);
        add(btnSoundOff);
            btnSoundOn.addActionListener(on);
               btnSoundOff.addActionListener(off);
    }

  class On implements ActionListener {

```
    @Override
    public void actionPerformed(ActionEvent event) {
        PanMain.panOption.setVisible(true);


    }
}

class Off implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent event) {
        PanMain.panOption.setVisible(true);


    }
}
```

}

**Comment by DunkehX** [comment]
Please post your full computer specs. Your description is quite unclear.
Thankyou - 
Donkeh

**Comment by DunkehX** [comment]
Hello,
Please attach a image of your full computer specs. You may lack ram required to perform your operation properly. Please refer to this site to download  more. http://www.downloadmoreram.com/

Thankyou - 
Ariana

**Comment by aiWebster** [comment]
Thanks for the help. Issue solved.
