### ISSUE TITLE
Requesting Deletion of Branch

### ISSUE THREAD

**Issue by dSPECIALUnkey** [zlindner/ClickManiaMMXV#3]
Hi there Admin,
Could you please delete the Dunkeh-Branch, I fear I've broken it. I've made a new branch called dÜnkey and that will be my main branch. Cheers.

**Comment by Vanillaa** [comment]
He the delete button sir.

**Comment by aiWebster** [comment]
hit the delete button sir.

**Comment by dSPECIALUnkey** [comment]
Hi there Vanillaa, I fear I cannot find the delete button anywhere. Could you please provide me a screen shot of sorts. Much appreciated, Cheers
dÜnkey

**Comment by aiWebster** [comment]
Here's a possible solution to your problem. https://github.com/blog/1377-create-and-delete-branches Hope I can help.
Chao..

**Comment by dSPECIALUnkey** [comment]
Hi again Vanillaa, I feel you may have posted the wrong link (although I had quite the giggle). Still requesting help from an admin. 
Cheers, 
dÜnkey

**Comment by zlindner** [comment]
I don't know what link you clicked on sir, but Admin Vanillaa's link was indeed a correct soultion, straight from the GitHub website.
Cheers, Management
