### ISSUE TITLE
Upgrade mishap

### ISSUE THREAD

**Issue by zlindner** [zlindner/ClickManiaMMXV#6]
Dear whomever it concerns,
Whenever I click on an upgrade and do not have the required funds, it proclaims that I have "Insufficient Funds", which is correct. BUT if I gain the $100, return to the upgrades panel it states, yet again, that I am "lacking" in the funds department; if you are picking up what I am putting down.
Cheers,
zlindner

**Comment by dSPECIALUnkey** [comment]
Hey there Mr. Lindner,
The development team of this project had the perception that the average player of our game had an IQ  level of  at-least 12. I am sincerely sorry, it seems we were sadly mistaken. The dev team is currently working on fixing this issue for "less competent" players.
Cheers,
Dev. dünkey

**Comment by zlindner** [comment]
Dear Dev. dünkey,
I don't appreciate the way you are speaking to me, especially since I JUST pointed out a flaw in your java class. I also don't believe that you should be talking to me as if you are an educated individual yourself; exhibit A: "its seems we WHERE sadly mistake" - please learn the difference between where and were.
Cheers, 
zlindner

**Comment by dSPECIALUnkey** [comment]
Hi there Mr. Lindner,
It seems you may be having vision issues. If you look closely you can notice it is indeed spelled "were".
Cheers,
Dev. dünkey

**Comment by dSPECIALUnkey** [comment]
Issue fixed in latest build, will be pushed soon.
